INSERT INTO priceList (item_name, price) VALUES ('Group Class', 10);
INSERT INTO priceList (item_name, price) VALUES ('Private Class', 50);
INSERT INTO priceList (item_name, price) VALUES ('Monthly Membership', 25);
INSERT INTO priceList (item_name, price) VALUES ('Monthly Free Group Class', 0);
INSERT INTO priceList (item_name, price) VALUES ('Monthly Free Private Class', 0);
INSERT INTO priceList (item_name, price) VALUES ('Water Bottle', 2);
INSERT INTO priceList (item_name, price) VALUES ('Protein Bar', 3);
INSERT INTO priceList (item_name, price) VALUES ('Protein Shake', 5);
INSERT INTO priceList (item_name, price) VALUES ('T-Shirt', 10);
INSERT INTO priceList (item_name, price) VALUES ('Sweatpants', 15);
INSERT INTO priceList (item_name, price) VALUES ('Sweatshirt', 20);
INSERT INTO priceList (item_name, price) VALUES ('Sneakers', 50);